import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ResizableComponent from "@/components/Resizable/ResizableComponent";

const inter = Inter({ subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

<html lang="en">
<body className={inter.className + ' min-h-screen'}>
    <div className="w-full">
      {/* Your Next.js component content goes here */}
      {/* <div className="w-[600px] md:w-full">
        <Navbar />
      </div> */}
      <div className="w-full">
        <ResizableComponent>{children}</ResizableComponent>
      </div>
    </div>
    <main className='p-5'>
        {children}
    </main>
</body>
</html>
  );
}
